### ISSUE TITLE
Applicaton error on Firefox

### ISSUE THREAD

**Issue by munterkalmsteiner** [davide-marchiori/k-alpha#2]
Uploading a csv file (for example the sample data provided in the usage notes) leads to the following error:
```Application error: a client-side exception has occurred (see the browser console for more information).```

In the dev console, I see the following error:
```TypeError: c.lastModifiedDate is undefined```

Firefox 129.0.1 (64-bit) on Linux.
Using Chrome the calculation works fine.

**Comment by davide-marchiori** [comment]
Dear Michael,
thank you very much for pointing this out. I have just released a newer version that addresses this issue.

The issue was created by the use of a deprecated method (file.lastModifiedDate) no longer supported by Firefox.
Overall, in this new version of the K-alpha calculator, all packages have been updated to the latest version, and the logic for error checking in file inputs has been improved.

Importantly, the algorithm for the computation of the K-alpha index **has not** been revised.

Thanks for using our tool!
Best regards,

Davide
